apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-app
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
